print('='*40)
print('     LOCADORA DE VEÍCULOS RECIFE     ')
print('='*40)
print(' ')
km = float(input('Informe os Km percorridos: '))
diaria = float(input('Informe a quantidade de diárias: '))
kmrodado = (km*0.20)
valordiaria = (diaria*90)
total = (kmrodado+valordiaria)
print('O valor de seu aluguel para {} diárias é de R${:.2f}.'.format(diaria, total))
