print('Conversor de Moedas')
print(' ')
reais = float(input('Quantos reais você quer converter? '))
dolar = float(reais/4.90)
euro = float(reais/5.342)
libra = float(reais/6.2)
print('Valor em Dólar: {:.2f}'.format(dolar))
print('Valor em Euro: {:.2f}'.format(euro))
print('Valor em Libra: {:.2f}'.format(libra))
